data_combine_node:
  ros__parameters:
    
    # 话题配置
    topics:
      combined_cloud: "/combined_cloud"
      combined_imu: "/cloud_registered_body/imu"
      lidar1: "/livox/lidar_192_168_2_144"
      lidar2: "/livox/lidar_192_168_1_112"
      imu: "/livox/imu_192_168_2_144"

    # lidar1 保持参考坐标系，不做额外变换
    lidar1:
      roll: 0.0        
      pitch: 0.0     
      yaw: 0.0         
      tx: 0.0           
      ty: 0.0            
      tz: 0.0             

    # lidar2 相对于 lidar1 的变换
    lidar2:
      roll: 3.14159       # 绕 X 轴旋转 180°
      pitch: 0.0
      yaw: 0.0
      tx: 0.0
      ty: 0.0
      tz: 0.07            # 沿 Z 正轴平移 70mm